<?php /** @var $block \CodeZee\Captcha\Block\Captcha */ ?>
<?php if ($block->isEnabled()): ?>
    <?php if($block->useGoogle()): ?>
        <script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>
        <div class="g-recaptcha" data-sitekey="<?= $block->getSiteKey();?>"></div>
    <?php else: ?>
        <div class="num_captcha_container">
            <b>Please complete the following equation to prove you're human.</b><br />
            <div class="equation">
                <span id="rand_1"><?php echo rand(1, 20) ?></span>&nbsp;&plus;&nbsp;<span id="rand_2"><?php echo rand(1, 20) ?></span>&nbsp;&equals;&nbsp;<input id="num_captcha" name="login[num_captcha]" type="text" />
                <input type="hidden" class="controller" value="<?php echo $this->getUrl('codezeecaptcha/index/captchaerror'); ?>" />
            </div>
        </div>
        <script type="text/javascript">
            require(['jquery','captchajs'],function($){
                $(window).load(function() {
                    return;
                });
            });
        </script>
     <?php endif; ?>
<?php endif; ?>
